[package]
name = "rust_engine"
version = "0.1.0"
edition = "2024"
default-run = "rust_engine"

[dependencies]
axum = { version = "0.8.9", features = ["multipart"] }
minijinja = { version = "2.24.0", features = ["json", "loader"] }
rayon = "1.12.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tower-http = { version = "0.7.1", features = ["fs", "cors"] }
